### ISSUE TITLE
`render deploy new` is inconsistent with how Render uses the term "deploy"

### ISSUE THREAD

**Issue by jakemalachowski** [render-oss/render-cli#1]
Generally, a deploy refers to an instance of rolling out a change to a service. My expectation is that `render deploy new` would allow me to initiate a manual deploy of a Render service. Instead, it takes me to the Render Blueprint page. I would expect this command to be named `render blueprint new` instead.

**Comment by eropple** [comment]
Interesting - that's good feedback, thanks. To me, `render blueprint new` should walk you through _building_ a render.yaml file, not deploying one. Thoughts?

**Comment by jakemalachowski** [comment]
`new` when deploying a blueprint is consistent with the naming on our dashboard (button name in screenshot). I'll defer to you on if this is reason enough to use `new` in the CLI. I do think it would be most natural that whatever verb we use for blueprints should be consistent when creating other service types as well (web services, postgres, etc.).

An alternative name for building a Blueprint could be `generate`.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/5766239/200073249-3dcd4090-7e7d-4575-b7ca-2aa5223edda9.png">

**Comment by eropple** [comment]
Yeah, that naming server-side has always made me scratch my head--you aren't creating a blueprint, you're creating a stack _from_ a blueprint.

Maybe `render blueprint deploy`? @anurag, any thoughts?

**Comment by anurag** [comment]
Terminology: [render new blueprint instance](https://slab.render.com/posts/render-blueprints-1v3nie65)

If we're going to use this to generate a blueprint YAML, we should probably use `render blueprint new`?

**Comment by eropple** [comment]
We're not generating one here (that's a later feature) - we're just kicking it off in the dashboard.

**Comment by eropple** [comment]
renamed to `render blueprint launch`, we can mess with it more later
