### ISSUE TITLE
`--profile` global flag doesn't seem to be respected

### ISSUE THREAD

**Issue by elauffenburger** [render-oss/render-cli#2]
I tried using an alternate profile, but it looks like `default` was used instead. `RENDERCLI_PROFILE` _was_ respected, though!

I suspect the issue is just respecting the flag here: https://github.com/renderinc/render-cli/blob/d589784d2c9444a619f5eaa257e0b3e56a6f0140/config/index.ts#L81

**Comment by eropple** [comment]
TODO: check region too

**Comment by eropple** [comment]
handled for next release
