### ISSUE TITLE
Windows package

### ISSUE THREAD

**Issue by eropple** [render-oss/render-cli#35]
Definitely chocolatey, maybe scoop?

**Comment by AdrianoCahete** [comment]
Don't forget about [winget](https://github.com/microsoft/winget-cli)!

**Comment by eropple** [comment]
WinGet may be doable, as it supports static executable symlinking. We'll see what we can do; the support for package-update notification seems a little janky.

**Comment by eropple** [comment]
Chocolatey is done; we will revisit WinGet later when we have some more bandwidth.

**Comment by eparizzi-clevertech** [comment]
> Chocolatey is done; we will revisit WinGet later when we have some more bandwidth.

Where? There's no rendercli package in Chocolatey...

**Comment by eropple** [comment]
I'd pushed one and gotten it verified to Chocolatey, the last I knew about it. But I no longer work at Render. You'll have to ask them, probably by email.
