### ISSUE TITLE
Error installing on Mac OS 13.3.1 M2 processor

### ISSUE THREAD

**Issue by dlikhten** [render-oss/render-cli#58]
- using ZSH, seems like that shouldn't matter at all, but just mentioning it just in case.

\> brew tap render-oss/render
\> brew install render
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#################################################################################################################################################################################### 100.0%
==> Fetching render-oss/render/render
==> Cloning https://github.com/render-oss/render-cli.git
Updating /Users/dlikhten/Library/Caches/Homebrew/render--git
==> Checking out tag v0.1.6
HEAD is now at c0de4b6 Merge pull request #57 from robdimarco-render/robdimarco-render/SVC-1626-fix-build-issue
HEAD is now at c0de4b6 Merge pull request #57 from robdimarco-render/robdimarco-render/SVC-1626-fix-build-issue
==> Installing render from render-oss/render
==> make build-completions
Last 15 lines from /Users/dlikhten/Library/Logs/Homebrew/render/01.make:
		--allow-net \
		--allow-read \
		--allow-run \
		--allow-write \
		--allow-env \
		--target=aarch64-apple-darwin \
		--output=./bin/render \
		./entry-point.ts
Check file:///private/tmp/render-20230517-29577-77kjnp/entry-point.ts
error: TS2345 [ERROR]: Argument of type '{}' is not assignable to parameter of type 'string'.
            if (deployIds && !deployIds.has(msg.deployID)) {
                                            ~~~~~~~~~~~~
    at file:///private/tmp/render-20230517-29577-77kjnp/commands/services/tail.ts:93:45
make[1]: *** [build-macos-aarch64] Error 1
make: *** [build-local] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/render-oss/homebrew-render/issues

**Comment by lazyatom** [comment]
I see this, not using `zsh` as the shell either.

**Comment by robdimarco-render** [comment]
Sorry about the problem. I have pushed a new release (v0.1.7) that should fix this error.

**Comment by dlikhten** [comment]
Confirmed, 0.1.7 works.
